# Paths configuration
paths:
  base_paths:
    obi: '/victoriapvc/data/'
    leia: '/victoriapvc/data/'
  server: 'obi'
  data_path_key: 'obi_log_big_0' #TODO: change me

# Training configuration
training:
  seed_list: [0]
  model_name_base: "replicate_shun_sota"
  checkpoint_dir: ""
  wandb_id: ""
  resume_from_epoch: 0

# Model architecture
model:
  patch_size: [5, 256]
  dim: 384
  depth: 5
  heads: 6
  mlp_dim_ratio: 4
  dim_head: 64
  T5_style_pos: true
  nClasses: 40
  nClasses_2: null
  dropout: 0.35
  input_dropout: 0.2

# Data preprocessing
data:
  maxDay: null
  restricted_days: [ ] #TODO: change me to [] if not exclude day 0 and 1
  whiteNoiseSD: 0.2
  gaussianSmoothWidth: 2.0
  constantOffsetSD: 0.05
  include_original: True
  include_stretched_samples: True
  include_prolonged_samples: False
  stretch_range: [1.5, 5]

# Masking configuration
masking:
  mask_token_zero: false
  num_masks_channels: 0
  max_mask_channels: 0
  max_mask_pct: 0.075
  num_masks: 20
  dist_dict_path: '/home3/skaasyap/willett/outputs/dist_dict.pt'
  consistency: false
  consistency_scalar: 0.2

# Optimization
optimization:
  AdamW: true
  learning_scheduler: 'multistep'
  lrStart: 0.001
  lrEnd: 0.001
  l2_decay: 1e-5
  beta1: 0.90
  beta2: 0.999
  batchSize: 64
  n_epochs: 500
  milestones: [300]
  gamma: 0.1

# DANN configuration
dann:
  normalize_features_for_discriminator: False # to make target feature norm constrained... otherwise discrimintor can win by making norm veyr big and encoder will learn to make norm veyr small 
  reduce_entropy_loss_weight: 0.00
  kl_phone_prior_loss_weight: 0.00 #0.05
  weighted_ctc_loss: False #False
  binary_cross_entropy_loss: False
  mean_pool_for_discriminator: False
  use_afn: False
  # afn_weight: 1e-3
  # afn_mode: "hafn" # or "hafn" from Larger Norm More Transferable paper
  # afn_R: 30.0 # only used when afn_mode is "hafn"
  # afn_delta_r: 1.0 # only used when afn_mode is "safn"
  emb_regularization_weight: null # this and use_afn should not be used together
  emb_regularization: null # l2, variance, temporal_smoothness
  noise_augmentation: False
  normalize_features: False  # normalize before masked_mean_pool, if you have emb_regularization, emb_regularization_weight >0, this should be False
  dom_loss_type: 'mean' # "sum", "mean", "softmax", "softmax_asymmetric"
  softmax_w_detach: False # only used when dom_loss_type is 'softmax' or 'softmax_asymmetric'
  temperature: 1.0 # only used when dom_loss_type is 'softmax'
  use_spectral_norm: False
  truely_mdan: True # True: source-i vs target, False: source-i vs all other sources + target
  mdan_allvsall: False # truely_mdan must be False. True: source-i vs all other sources + target, False: source-i vs target
  bottleneck_dim: null
  use_target_loss: True # should always be True for MDAN-GRL
  dann_alpha_type: 'alternative' 
  phase: 24 # only used when dann_alpha_type is 'alternative'
  use_ce_loss: False # no related
  use_me_loss: False # no related
  use_binary_loss: True # no related
  rep_layer_idx: 2
  dann_lambda: 0.5
  lambda_src: 1.0 # not related, we set it as 0.5 in code
  lambda_tgt: 0.8 # revived - now is 0.5 (l_src + lambda_tgt * l_tgt)
  dann_warmup_epochs: 0
  dann_lr_multiplier: 1.0
  dann_weight_decay: null
  domain_hidden: 256
  domain_dropout: 0.0
  use_amp: True
  grad_clip: null
  alpha_max: 1.0
  alpha_max_epochs: null
  schedule: 'linear'
  dann_optimizer: 'AdamW'
  linear_discriminator: False
  dann_dropout_channel_prob: 0.2
  detach_discriminator_from_encoder: False
  non_blank_weighting: False
  domain_entropy_weight: 0.0

# Other settings
other:
  ventral_6v_only: false
  extra_notes: "Cross-session DANN MDAN-GRL REAL"
  wandb_project: 'Shun-param-sweep'
  wandb_entity: 'victoriazhang-projects'
